# Generated by Django 3.1.7 on 2024-07-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210318_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(blank=True, default='def_user.png', null=True, upload_to='users/', verbose_name='şəkil'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nick'),
        ),
    ]
